In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from keras.metrics import mean_absolute_error

# A

In [2]:
file = pd.read_csv('./housing.csv', delim_whitespace=True)
file

0.00632  18.00  2.310  0  0.5380  6.5750  65.20  4.0900  1  296.0  15.30  \
0    0.02731    0.0   7.07  0   0.469   6.421   78.9  4.9671  2  242.0   17.8   
1    0.02729    0.0   7.07  0   0.469   7.185   61.1  4.9671  2  242.0   17.8   
2    0.03237    0.0   2.18  0   0.458   6.998   45.8  6.0622  3  222.0   18.7   
3    0.06905    0.0   2.18  0   0.458   7.147   54.2  6.0622  3  222.0   18.7   
4    0.02985    0.0   2.18  0   0.458   6.430   58.7  6.0622  3  222.0   18.7   
..       ...    ...    ... ..     ...     ...    ...     ... ..    ...    ...   
500  0.06263    0.0  11.93  0   0.573   6.593   69.1  2.4786  1  273.0   21.0   
501  0.04527    0.0  11.93  0   0.573   6.120   76.7  2.2875  1  273.0   21.0   
502  0.06076    0.0  11.93  0   0.573   6.976   91.0  2.1675  1  273.0   21.0   
503  0.10959    0.0  11.93  0   0.573   6.794   89.3  2.3889  1  273.0   21.0   
504  0.04741    0.0  11.93  0   0.573   6.030   80.8  2.5050  1  273.0   21.0   

     396.90  4.98  24.00  
0    396.90  9.14   21.6  
1    392.83  4.03   34.7  
2    394.63  2.94   33.4  
3    396.90  5.33   36.2  
4    394.12  5.21   28.7  
..      ...   ...    ...  
500  391.99  9.67   22.4  
501  396.90  9.08   20.6  
502  396.90  5.64   23.9  
503  393.45  6.48   22.0  
504  396.90  7.88   11.9  

[505 rows x 14 columns]

In [3]:
file_np = file.to_numpy()
num_rows, num_cols =file_np.shape 
print("Initial input_custom is: \n" , file_np )
print("***********************")
print(" Number of Rows are :",num_rows,"\n and \n", "Number of Colums are:" , num_cols)

Initial input_custom is: 
 [[2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 [3.2370e-02 0.0000e+00 2.1800e+00 ... 3.9463e+02 2.9400e+00 3.3400e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]
***********************
 Number of Rows are : 505 
 and 
 Number of Colums are: 14


# B

In [4]:
y = file_np [:,-1]

# C

In [5]:
# 20% Test & 80% Training
Training_Data_Number = int(np.round_((80/100)*num_rows))
Testimg_Data_Number = int(num_rows - Training_Data_Number)
print(Training_Data_Number)
print("***********************")
print(Testimg_Data_Number)

404
***********************
101


In [6]:
#Shuffling And Split generated Data to Train and Test
trained =file_np[0:Training_Data_Number,:]
#np.random.shuffle(trained)
Tested = file_np[Training_Data_Number:,:]
#np.random.shuffle(Tested) 

In [7]:
X_train = trained[:, 0:num_cols-1]
Y_train = trained[:, num_cols-1]
Y_train = np.reshape(Y_train,(Training_Data_Number,1))
print("X_train is: \n" , Y_train)
#print("***********************")
#print(X_train[0])
#print(Y_train[0])
print("***********************")
X_test = Tested[:, 0:num_cols-1]
Y_test = Tested[:, num_cols-1]
Y_test = np.reshape(Y_test,(Testimg_Data_Number,1))
print("X_test is: \n" , X_test)
#print("***********************")
#print(X_test[0])
#print(Y_test[0])

X_train is: 
 [[21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]
 [15. ]
 [18.9]
 [21.7]
 [20.4]
 [18.2]
 [19.9]
 [23.1]
 [17.5]
 [20.2]
 [18.2]
 [13.6]
 [19.6]
 [15.2]
 [14.5]
 [15.6]
 [13.9]
 [16.6]
 [14.8]
 [18.4]
 [21. ]
 [12.7]
 [14.5]
 [13.2]
 [13.1]
 [13.5]
 [18.9]
 [20. ]
 [21. ]
 [24.7]
 [30.8]
 [34.9]
 [26.6]
 [25.3]
 [24.7]
 [21.2]
 [19.3]
 [20. ]
 [16.6]
 [14.4]
 [19.4]
 [19.7]
 [20.5]
 [25. ]
 [23.4]
 [18.9]
 [35.4]
 [24.7]
 [31.6]
 [23.3]
 [19.6]
 [18.7]
 [16. ]
 [22.2]
 [25. ]
 [33. ]
 [23.5]
 [19.4]
 [22. ]
 [17.4]
 [20.9]
 [24.2]
 [21.7]
 [22.8]
 [23.4]
 [24.1]
 [21.4]
 [20. ]
 [20.8]
 [21.2]
 [20.3]
 [28. ]
 [23.9]
 [24.8]
 [22.9]
 [23.9]
 [26.6]
 [22.5]
 [22.2]
 [23.6]
 [28.7]
 [22.6]
 [22. ]
 [22.9]
 [25. ]
 [20.6]
 [28.4]
 [21.4]
 [38.7]
 [43.8]
 [33.2]
 [27.5]
 [26.5]
 [18.6]
 [19.3]
 [20.1]
 [19.5]
 [19.5]
 [20.4]
 [19.8]
 [19.4]
 [21.7]
 [22.8]
 [18.8]
 [18.7]
 [18.5]
 [18.3]
 [21.2]
 [19.2]
 [20.4]
 [19.3]
 [22. ]
 [20.3]
 [20.5]
 [17.3]
 [

# D

In [8]:
mean =  np.mean(X_train) 
standard_deviation = np.std( X_train)
X_train_scaled = (X_train -mean) /standard_deviation

In [9]:
#print(X_train_scaled)

In [10]:
mean =  np.mean(X_test) 
standard_deviation = np.std( X_test)
X_test_scaled = (X_test -mean) /standard_deviation
#print(X_test_scaled)

# E

In [11]:
# Creating our model
from keras import models
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import layers
from keras.metrics import mean_absolute_error

def mlp():
    model = models.Sequential()

    model.add(layers.Dense(256, activation='relu', input_shape=(13,)))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(16, activation='relu'))
    
    model.add(layers.Dense(1))
    
    #model.summary()
    model.compile(optimizer='rmsprop', loss="mse", metrics=['mean_absolute_error'])
    return model

# F

In [12]:
from sklearn.model_selection import KFold
folds = KFold(n_splits=5, random_state=None)
mae = []
 
for i, j in folds.split(X_train_scaled):
    model = mlp()

    x_fold_train, x_fold_valid = X_train_scaled[i,:], X_train_scaled[j,:]
    y_fold_train, y_fold_valid = Y_train[i], Y_train[j]

    model.fit(x_fold_train, y_fold_train, epochs=4, batch_size=1)
    predict = model.predict( x_fold_valid).reshape( y_fold_valid.shape)

    mae.append(mean_absolute_error( y_fold_valid, predict))

Epoch 1/4
323/323 [==============================] - 2s 2ms/step - loss: 184.4718 - mean_absolute_error: 9.8373
Epoch 2/4
323/323 [==============================] - 1s 3ms/step - loss: 92.2989 - mean_absolute_error: 7.1361
Epoch 3/4
323/323 [==============================] - 1s 2ms/step - loss: 85.4477 - mean_absolute_error: 6.8070
Epoch 4/4
3/3 [==============================] - 0s 2ms/step
Epoch 1/4
323/323 [==============================] - 1s 1ms/step - loss: 146.0709 - mean_absolute_error: 8.6204
Epoch 2/4
323/323 [==============================] - 0s 1ms/step - loss: 86.1961 - mean_absolute_error: 6.8039
Epoch 3/4
323/323 [==============================] - 0s 1ms/step - loss: 85.2756 - mean_absolute_error: 6.8605
Epoch 4/4
3/3 [==============================] - 0s 1ms/step
Epoch 1/4
323/323 [==============================] - 1s 2ms/step - loss: 107.9975 - mean_absolute_error: 7.3745
Epoch 2/4
323/323 [==============================] - 1s 2ms/step - loss: 69.2698 - mean_absolute_e

In [13]:
test_mse, test_mae = model.evaluate(X_test_scaled, Y_test)
print('Loss of testset (MSE):', test_mse)
print('Metric of testset (MAE):', test_mae)

4/4 [==============================] - 0s 2ms/step - loss: 19.2286 - mean_absolute_error: 3.1672
Loss of testset (MSE): 19.228641510009766
Metric of testset (MAE): 3.1671502590179443
